name: Development Issue
description: Report an issue encountered when working on code in this repo.
title: "[dev]: "
labels: "bug"
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Basic info about your environment, such as operating system and version of tools (eg. Python, Rust, Solidity etc.).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information that could be useful, like screenshots etc.
    validations:
      required: false
