name: Test Go Examples

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test Go Examples
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/developer-hub-go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install dependencies
        run: go get .
      - name: Run Tests
        run: |
          go test ./coston2 -v
          go test ./flare -v
      # - name: Lint with golangci-lint
      #   uses: golangci/golangci-lint-action@v6
      #   with:
      #     version: v1.60
